### PR TITLE
Nbgrader refactor

### PR DESCRIPTION
**Pull request by ellisonbg**
Here is a PR that refactors the ansible stuff for nbgrader:

* Uses nbgrader's new approach to installing nbextension's and serverextension (just use the regular jupyter commands).
* Allows for multiple formgrade instances.

I still need to test this on my deployment before we merge...

### CODE REVIEW

**Comment by ellisonbg** [comment]
@jhamrick

**Comment by ellisonbg** [comment]
Right now master is broken...going to merge this and iterate/fix things along the way...

**Comment by randy3k** [comment]
How should I access formgrade with this PR?
I tried https://www.example.com/services/formgrader-course101 but it doesn't work.

**Comment by randy3k** [comment]
Oh, it should be https://www.example.com/services/formgrade-course101 instead of formgrader

Somehow, it is not consistent with nbgrader documentation https://nbgrader.readthedocs.io/en/stable/configuration/jupyterhub_config.html

**Comment by willingc** [comment]
Hi @randy3k!

Thanks for the question and I'm glad you solved your question. Technically, the Ansible scripts here as a specific deployment and the more general nbgrader documentation are both correct. Yet, I agree with you that the inconsistent naming is confusing. Thanks for pointing that out in the documentation. If you find other parts of the docs confusing, please do let us know.

@jhamrick, Do you want me to do a PR to update the nbgrader docs?

**Comment by jhamrick** [comment]
@willingc yes, that would be awesome, thank you!

**Pull request merged**
