### PR TITLE
updates

### LINKED ISSUE #25: ubuntu 16.04
Does it work in ubuntu 16.04? 
Which versions of ubuntu and ansible this script was tested against?
I encountered some problems - some packages are not installed.

### LINKED ISSUE #26: config-http-proxy not installing
With a fresh deployment, I get an error:

```
[I 2016-10-02 15:50:13.731 JupyterHub app:624] Loading cookie_secret from /srv/jupyterhub/cookie_secret
[I 2016-10-02 15:50:13.819 JupyterHub app:1232] Hub API listening on http://127.0.0.1:8081/hub/
[W 2016-10-02 15:50:13.822 JupyterHub app:960] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
[I 2016-10-02 15:50:13.822 JupyterHub app:969] Starting proxy @ http://65.61.190.162:8000/
[E 2016-10-02 15:50:13.824 JupyterHub app:977] Failed to find proxy ['configurable-http-proxy']
    The proxy can be installed with `npm install -g configurable-http-proxy`
```

Running `conda list` does not show the configurable-http-proxy package.

@minrk @willingc any ideas?

### LINKED ISSUE #27: nginx not restarting/loading new config
A fresh deployment on ubuntu 14 LTS needed an extra `service nginx restart` before it would run.

@minrk @willingc

### PR DESCRIPTION
**Pull request by minrk**
- set default user back to root in ansible.cfg (this can be overridden in vars, but root should be left as the default)
- bump miniconda to 4.1.11
- install a few more things with conda instead of pip, now that we are using conda-forge
- minor apt tweaks
- use certbot-auto tool for letsencrypt
- autorenew letsencrypt certs with cron

I did have to include a workaround for letsencrypt due to a problem in the pycparser wheel, but that should be short-lived (https://github.com/certbot/certbot/pull/3575)

With this PR, I was able to run a deployment start to finish with a fresh Ubuntu 14.04 machine on Rackspace without errors.

closes #25
closes #26
closes #27

cc @ellisonbg

I wasn't able to reproduce the errors you saw in #26, #27. What options did you specify, and what exact version of this repo were you using? Did you use letsencrypt or your own SSL certs?

What do you see for `conda config --get` and `conda config get --system`?

### CODE REVIEW

**Comment by minrk** [comment]
I also did a fresh deploy, verifying that this works on Ubuntu 16.04 (#25)

**Comment by ellisonbg** [comment]
- `conda config --get` is empty

```
conda config --get --system
--add channels 'defaults'   # lowest priority
--add channels 'conda-forge'   # highest priority
--set show_channel_urls True
``
```

**Comment by ellisonbg** [comment]
I have used my own SSL cert.

**Comment by zonca** [comment]
+1, did a fresh install on SDSC Cloud OpenStack Ubuntu 16.04, no issues. /cc @kevincoakley

**Comment by willingc** [comment]
Question for @minrk: Is there a reason that `deploy.yml` install python 2.7?

**Comment by zonca** [comment]
@willingc `ansible` requires python 2.7 (!!) and that is not installed anymore on 16.04 by default

**Comment by kevincoakley** [comment]
Ansible 2.1 should work on 16.04 and python 3 with the [Ansible PPA](https://launchpad.net/~ansible/+archive/ansible) installed.

**Comment by minrk** [comment]
@kevincoakley thanks! I'll do another test deployment requiring ansible 2.1 and removing the py27 step, just to be sure.

**Comment by willingc** [comment]
@minrk when you do the test deployment, would you capture the console and send me the commands (input/output)? Thanks!

**Comment by minrk** [comment]
@willingc will do

**Comment by minrk** [comment]
Removed the py27 install, bumped requirement to ansible 2.1 (with a check), and a fresh deployment does indeed work on 16.04.

[the log](https://gist.github.com/7c3d6d3c978a1183e486fe73b1f62fd5)

**Comment by ellisonbg** [comment]
We should probably merge this - I can try another deployment based on these changes soon...

**Comment by willingc** [comment]
Thanks @minrk. I've gone ahead and merged this based on @ellisonbg's feedback. We may wish to clarify in the README (Ubuntu 16.04 LTS instead of most recent stable).

**Pull request merged**
