### PR TITLE
update license to Jupyter

### PR DESCRIPTION
**Pull request by minrk**
@ellisonbg what's the best way to credit Cal Poly contributors to the Data 301 starting point here?

### CODE REVIEW

**Comment by ellisonbg** [comment]
I would just mention that this was started at Cal Poly by Brian Granger and
Jon Frederic. Originally Jon did some work on this in a different version,
but I am the sole dev of this version.

On Thu, Apr 14, 2016 at 7:19 AM, Min RK notifications@github.com wrote:

> @ellisonbg https://github.com/ellisonbg what's the best way to credit
> 
> ## Cal Poly contributors to the Data 301 starting point here?
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/jupyterhub/jupyterhub-deploy-teaching/pull/1
> Commit Summary
> - update license for JupyterHub
> 
> File Changes
> - _M_ LICENSE
>   https://github.com/jupyterhub/jupyterhub-deploy-teaching/pull/1/files#diff-0
>   (4)
> 
> Patch Links:
> - https://github.com/jupyterhub/jupyterhub-deploy-teaching/pull/1.patch
> - https://github.com/jupyterhub/jupyterhub-deploy-teaching/pull/1.diff
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyterhub/jupyterhub-deploy-teaching/pull/1

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
In the LICENSE or README for that notice, then?

**Comment by willingc** [comment]
@minrk @ellisonbg As an FYI, I put an [acknowledgment page](https://test-jupyterhub-teaching.readthedocs.org/en/sphinx-docs/acknowledgment.html) at the end of the Sphinx docs PR yesterday. Please let me know if you want that modified. Thanks.

**Comment by willingc** [comment]
Merging this since the docs mention on the index page and on the acknowledgement page. I'll loop back and put in the README. We can always add to LICENSE if desired.

**Pull request merged**
