### PR TITLE
More kernels

### PR DESCRIPTION
**Pull request by randy3k**
- added R kernel
- make bash kernel optional

### CODE REVIEW

**Comment by ellisonbg** [comment]
Awesome, thanks for working on this. Now that we are using conda for installing the Python kernel, I wonder if that makes sense for R as well? @minrk thoughts?

**Comment by ellisonbg** [comment]
Also, I think this should install a larger set of R packages by default. Maybe the same set as R Studio?

**Comment by randy3k** [comment]
The conda R channel is not always updated, so I decided to use apt get instead.

**Comment by minrk** [comment]
If it were me, I would use conda for it, but I trust people who actually teach with R to make a better choice. I'm happy to merge this as-is, and we can consider conda for R at a later point.

**Pull request merged**
